server:
  port: 8081

spring:
  application:
    name: stats
  datasource:
    password: 123
    url: jdbc:postgresql://localhost:5432/task_stats
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

